<?php

    if ($messenger->hasMessages()) 
    {
        print_r( $messenger->getMessages() );
    }
    if ($messenger->hasInfoMessages()) 
    {
        print_r( $messenger->getInfoMessages() );
    }
    if ($messenger->hasSuccessMessages()) 
    {
        print_r( $messenger->getSuccessMessages() );
    }
    if ($messenger->hasWarningMessages()) 
    {
        print_r( $messenger->getWarningMessages() );
    }    
    if ($messenger->hasErrorMessages()) 
    {
        print_r( $messenger->getErrorMessages() );
    }
	
	
	
	
	